### ISSUE TITLE
Is this plugin compatible with Pelican 3.7?

### ISSUE THREAD

**Issue by kaffa** [mothsART/ace_editor#2]
I use .rst to generate .html in Pelican 3.7. 
But the ace_editor can't be embed to show this code in highlight.

```
.. code:: python

import os

print(os.sys.version)
```

I have already insert this line before tag `</body>` of base.html

`{{ ace_editor }}`

and my config is: 
```
PLUGIN_PATHS = ['/path-of-my/pelican-plugins/']
PLUGINS = [
    'ace_editor'
]
MARKDOWN = {
    'markdown.extensions.codehilite': {
        'css_class': 'literal-block',
        'linenums': False,
        'use_pygments': False
    }
}
```

I find the script has already been in my html, also I tried changing
```
var $pre_filter = $('pre.highlight');
```
to
```
var $pre_filter = $('pre.literal-block'); 
```
But the ace editor couldn't been show in the html page.
I wonder if this plugin is compatible with Pelican 3.7?

**Comment by mothsART** [comment]
You told me about a .rst file and MARKDOWN config... it's a little inconsistent.

If you're using Markdown, i suggest to you this config :

```
MARKDOWN = {
    'extension_configs': {
        'markdown.extensions.codehilite': {
            'css_class': 'highlight',
            'linenums': False,
            'use_pygments': False
        }
    }
}
```

In the case of restructuredtext, you need 2 dependencies :
```
pip install docutils Pygments
```

I will edit README.

Thanks to your feedback.
